# Generated by Django 5.1.4 on 2025-01-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="proifle_image",
            new_name="profile_image",
        ),
    ]
